fix: hour crontab (#31)
Sometimes there is a problem with the moment calculation result when the
scheduler is executed.

for example：

2024-09-25 11:00:00,000 ERROR 410 /4ms SCHEDULE /__schedule]
nodejs.Error: [egg-logrotator] rename /home/admin/logs/egg/egg-web.log,
found exception: targetFile
/home/admin/logs/egg/egg-web.log.2024-09-25_09 exists!!

The calculation result of moment is 9 instead of 10, causing an error.

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

- **Bug Fixes**
- Adjusted the scheduling of a task to run one minute past the hour,
improving timing accuracy for task execution.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->

Co-authored-by: shixia.ly <shixia.ly@antgroup.com>